"""Add insurer and product_category to Deal

Revision ID: 1ba014851fb3
Revises: 44bfaa64905f
Create Date: 2024-11-11 16:50:48.500344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba014851fb3'
down_revision = '44bfaa64905f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('insurer', sa.String(length=100), nullable=False))
    op.add_column('deal', sa.Column('product_category', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'product_category')
    op.drop_column('deal', 'insurer')
    # ### end Alembic commands ###
