"""Add address to Client, add fields to Lead, and add Comment model

Revision ID: 44bfaa64905f
Revises: 8254f88203ba
Create Date: 2024-11-11 00:00:55.210232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bfaa64905f'
down_revision = '8254f88203ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('lead', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('lead', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('lead', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'address')
    op.drop_column('lead', 'phone')
    op.drop_column('lead', 'email')
    op.drop_column('client', 'address')
    op.drop_table('comment')
    # ### end Alembic commands ###
