"""Add relationships for Lead to Deal conversion

Revision ID: 8254f88203ba
Revises: 
Create Date: 2024-11-10 22:02:04.004439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8254f88203ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('client_id', sa.Integer(), nullable=False))
    op.alter_column('deal', 'policy_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('deal', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('deal', 'renewal_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_foreign_key(None, 'deal', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal', type_='foreignkey')
    op.alter_column('deal', 'renewal_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('deal', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('deal', 'policy_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('deal', 'client_id')
    # ### end Alembic commands ###
